---
routine:
  name: "pick_n_place"
  tasks:
      
    - target: "arm" 
      pose:
        position:
          x: 0.11077
          y: -0.16598
          z: 0.058271
        orientation:
          x: -0.32288
          y: -0.5751
          z: -0.35788
          w: 0.661

    - target: "gripper"
      position: 1.0
          
    - target: "arm"
      pose:
        position:
          x: 0.1247
          y: -0.19031
          z: 0.057139
        orientation:
          x: -0.32602
          y: -0.57861
          z: -0.35897
          w: 0.65579
          
    - target: "gripper"
      position: 0.25
      
    - target: "arm"
      pose:
        position:
          x: 0.013342
          y: -0.10319
          z: 0.27606
        orientation:
          x: -0.41798
          y: -0.35225
          z: -0.59529
          w: 0.58894
          
    - target: "arm"
      pose:
        position:
          x: -0.1777
          y: -0.2515
          z: 0.16232
        orientation:
          x: 0.50247
          y: 0.20858
          z: 0.75091
          w: -0.37438
          
    - target: "gripper"
      position: 1.0
      
    - target: "arm"
      named_target: "home"
      
    - target: "gripper"
      position: 0.25
