# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - lerobot_arm_controller
    - lerobot_gripper_controller

  lerobot_arm_controller:
    type: FollowJointTrajectory
    joints:
      - shoulder_pan
      - shoulder_lift
      - elbow_flex
      - wrist_flex
      - wrist_roll
    action_ns: follow_joint_trajectory
    default: true
  lerobot_gripper_controller:
    type: GripperCommand
    joints:
      - gripper_joint
    action_ns: gripper_cmd
    default: true