# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    lerobot_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    lerobot_gripper_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

lerobot_arm_controller:
  ros__parameters:
    joints:
      - shoulder_pan
      - shoulder_lift
      - elbow_flex
      - wrist_flex
      - wrist_roll
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
lerobot_gripper_controller:
  ros__parameters:
    joint: gripper_joint