name: lerobot_build_check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened]

jobs:
  build:

    runs-on: ubuntu-22.04

    container:
      image: ghcr.io/dokyun-kim4/lerobot:latest
      
    steps:
      - name: Pull Repository
        uses: actions/checkout@v3
      
      - name: Test package build
        run: |
          cd ros_ws
          colcon build
